/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherRegisterRouteImport } from './routes/teacher/register'
import { Route as TeacherLoginRouteImport } from './routes/teacher/login'
import { Route as TeacherForgotPasswordRouteImport } from './routes/teacher/forgot-password'
import { Route as StudentSubscriptionPlansRouteImport } from './routes/student/subscription-plans'
import { Route as StudentResubscriptionPlansRouteImport } from './routes/student/resubscription-plans'
import { Route as StudentRegisterRouteImport } from './routes/student/register'
import { Route as StudentLoginRouteImport } from './routes/student/login'
import { Route as StudentForgotPasswordRouteImport } from './routes/student/forgot-password'
import { Route as StudentFailedSubscriptionRouteImport } from './routes/student/failed-subscription'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedTeacherRouteRouteImport } from './routes/_authenticated/teacher/route'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/student/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as StudentQuizIndexRouteImport } from './routes/student/quiz/index'
import { Route as StudentCoursesIndexRouteImport } from './routes/student/courses/index'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher/index'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as StudentCoursesCourseIDRouteImport } from './routes/student/courses/$courseID'
import { Route as AuthenticatedTeacherSettingsRouteRouteImport } from './routes/_authenticated/teacher/settings/route'
import { Route as AuthenticatedStudentSettingsRouteRouteImport } from './routes/_authenticated/student/settings/route'
import { Route as AuthenticatedStudentSubscribedRouteRouteImport } from './routes/_authenticated/student/_subscribed/route'
import { Route as AuthenticatedAdminSettingsRouteRouteImport } from './routes/_authenticated/admin/settings/route'
import { Route as StudentSettingInvoicesIndexRouteImport } from './routes/student/setting/invoices/index'
import { Route as AuthenticatedTeacherTrainingwheelgameIndexRouteImport } from './routes/_authenticated/teacher/trainingwheelgame/index'
import { Route as AuthenticatedTeacherSettingsIndexRouteImport } from './routes/_authenticated/teacher/settings/index'
import { Route as AuthenticatedTeacherCoursesIndexRouteImport } from './routes/_authenticated/teacher/courses/index'
import { Route as AuthenticatedStudentSettingsIndexRouteImport } from './routes/_authenticated/student/settings/index'
import { Route as AuthenticatedStudentPaymentMethodsIndexRouteImport } from './routes/_authenticated/student/payment-methods/index'
import { Route as AuthenticatedStudentInvoicesIndexRouteImport } from './routes/_authenticated/student/invoices/index'
import { Route as AuthenticatedStudentCourseTeachersIndexRouteImport } from './routes/_authenticated/student/course-teachers/index'
import { Route as AuthenticatedAdminTrainingwheelgameIndexRouteImport } from './routes/_authenticated/admin/trainingwheelgame/index'
import { Route as AuthenticatedAdminTeachersIndexRouteImport } from './routes/_authenticated/admin/teachers/index'
import { Route as AuthenticatedAdminStudentsIndexRouteImport } from './routes/_authenticated/admin/students/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'
import { Route as AuthenticatedStudentCourseTeachersTeacherIDRouteImport } from './routes/_authenticated/student/course-teachers/$teacherID'
import { Route as AuthenticatedAdminTeachersTeacherIDRouteImport } from './routes/_authenticated/admin/teachers/$teacherID'
import { Route as AuthenticatedAdminCoursesCourseIDRouteImport } from './routes/_authenticated/admin/courses/$courseID'
import { Route as AuthenticatedTeacherTrainingwheelgameCreateIndexRouteImport } from './routes/_authenticated/teacher/trainingwheelgame/create/index'
import { Route as AuthenticatedTeacherSettingsProfileIndexRouteImport } from './routes/_authenticated/teacher/settings/profile/index'
import { Route as AuthenticatedTeacherCoursesCreate_courseIndexRouteImport } from './routes/_authenticated/teacher/courses/create_course/index'
import { Route as AuthenticatedStudentSettingsBillingIndexRouteImport } from './routes/_authenticated/student/settings/billing/index'
import { Route as AuthenticatedStudentSubscribedTrainingwheelgameIndexRouteImport } from './routes/_authenticated/student/_subscribed/trainingwheelgame/index'
import { Route as AuthenticatedStudentSubscribedEnrolledcoursesIndexRouteImport } from './routes/_authenticated/student/_subscribed/enrolledcourses/index'
import { Route as AuthenticatedAdminTrainingwheelgameCreateIndexRouteImport } from './routes/_authenticated/admin/trainingwheelgame/create/index'
import { Route as AuthenticatedAdminSettingsProfileIndexRouteImport } from './routes/_authenticated/admin/settings/profile/index'
import { Route as AuthenticatedAdminSettingsGameCategoryIndexRouteImport } from './routes/_authenticated/admin/settings/game-category/index'
import { Route as AuthenticatedAdminSettingsCourseCategoryIndexRouteImport } from './routes/_authenticated/admin/settings/course-category/index'
import { Route as AuthenticatedAdminBlogsCreateIndexRouteImport } from './routes/_authenticated/admin/blogs/create/index'
import { Route as StudentSettingInvoicesInvoiceDetailsInvoiceIDRouteImport } from './routes/student/setting/invoices/invoice-details/$invoiceID'
import { Route as AuthenticatedTeacherTrainingwheelgameEditGameIDRouteImport } from './routes/_authenticated/teacher/trainingwheelgame/edit/$gameID'
import { Route as AuthenticatedTeacherCoursesEdit_courseCourseIdRouteImport } from './routes/_authenticated/teacher/courses/edit_course/$courseId'
import { Route as AuthenticatedTeacherCoursesCourse_studentsCourseIdRouteImport } from './routes/_authenticated/teacher/courses/course_students/$courseId'
import { Route as AuthenticatedTeacherCoursesCourse_detailsCourseIDRouteImport } from './routes/_authenticated/teacher/courses/course_details/$courseID'
import { Route as AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRouteImport } from './routes/_authenticated/student/_subscribed/enrolledcourses/$courseId'
import { Route as AuthenticatedAdminTrainingwheelgameEditGameIDRouteImport } from './routes/_authenticated/admin/trainingwheelgame/edit/$gameID'
import { Route as AuthenticatedAdminSamplePagesErrorsUnauthorizedRouteImport } from './routes/_authenticated/admin/sample-pages/errors/unauthorized'
import { Route as AuthenticatedAdminSamplePagesErrorsServerErrorRouteImport } from './routes/_authenticated/admin/sample-pages/errors/server-error'
import { Route as AuthenticatedAdminSamplePagesErrorsNotFoundRouteImport } from './routes/_authenticated/admin/sample-pages/errors/not-found'
import { Route as AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRouteImport } from './routes/_authenticated/admin/sample-pages/errors/maintenance-error'
import { Route as AuthenticatedAdminSamplePagesErrorsForbiddenRouteImport } from './routes/_authenticated/admin/sample-pages/errors/forbidden'
import { Route as AuthenticatedAdminSamplePagesAuthSignInRouteImport } from './routes/_authenticated/admin/sample-pages/auth/sign-in'
import { Route as AuthenticatedAdminSamplePagesAuthOtpRouteImport } from './routes/_authenticated/admin/sample-pages/auth/otp'
import { Route as AuthenticatedAdminSamplePagesAuthForgotPasswordRouteImport } from './routes/_authenticated/admin/sample-pages/auth/forgot-password'
import { Route as AuthenticatedAdminBlogsEditBlogIDRouteImport } from './routes/_authenticated/admin/blogs/edit/$blogID'
import { Route as AuthenticatedAdminBlogsBlogDetailsBlogIDRouteImport } from './routes/_authenticated/admin/blogs/blog-details/$blogID'
import { Route as AuthenticatedAdminSamplePagesAuthStudentSignUpRouteImport } from './routes/_authenticated/admin/sample-pages/auth/student/sign-up'
import { Route as AuthenticatedAdminSamplePagesAuthStudentcopySignUpRouteImport } from './routes/_authenticated/admin/sample-pages/auth/student copy/sign-up'

const AuthenticatedAdminCoursesIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/courses/',
)()
const AuthenticatedAdminBlogsIndexLazyRouteImport = createFileRoute(
  '/_authenticated/admin/blogs/',
)()

const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRegisterRoute = TeacherRegisterRouteImport.update({
  id: '/teacher/register',
  path: '/teacher/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher/login',
  path: '/teacher/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherForgotPasswordRoute = TeacherForgotPasswordRouteImport.update({
  id: '/teacher/forgot-password',
  path: '/teacher/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSubscriptionPlansRoute =
  StudentSubscriptionPlansRouteImport.update({
    id: '/subscription-plans',
    path: '/subscription-plans',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentResubscriptionPlansRoute =
  StudentResubscriptionPlansRouteImport.update({
    id: '/resubscription-plans',
    path: '/resubscription-plans',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const StudentRegisterRoute = StudentRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentForgotPasswordRoute = StudentForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentFailedSubscriptionRoute =
  StudentFailedSubscriptionRouteImport.update({
    id: '/failed-subscription',
    path: '/failed-subscription',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRouteRoute =
  AuthenticatedTeacherRouteRouteImport.update({
    id: '/_authenticated/teacher',
    path: '/teacher',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/_authenticated/student',
    path: '/student',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentQuizIndexRoute = StudentQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const StudentCoursesCourseIDRoute = StudentCoursesCourseIDRouteImport.update({
  id: '/courses/$courseID',
  path: '/courses/$courseID',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AuthenticatedTeacherSettingsRouteRoute =
  AuthenticatedTeacherSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedStudentSettingsRouteRoute =
  AuthenticatedStudentSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentSubscribedRouteRoute =
  AuthenticatedStudentSubscribedRouteRouteImport.update({
    id: '/_subscribed',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRouteRoute =
  AuthenticatedAdminSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesIndexLazyRoute =
  AuthenticatedAdminCoursesIndexLazyRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/courses/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminBlogsIndexLazyRoute =
  AuthenticatedAdminBlogsIndexLazyRouteImport.update({
    id: '/blogs/',
    path: '/blogs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/blogs/index.lazy').then(
      (d) => d.Route,
    ),
  )
const StudentSettingInvoicesIndexRoute =
  StudentSettingInvoicesIndexRouteImport.update({
    id: '/setting/invoices/',
    path: '/setting/invoices/',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const AuthenticatedTeacherTrainingwheelgameIndexRoute =
  AuthenticatedTeacherTrainingwheelgameIndexRouteImport.update({
    id: '/trainingwheelgame/',
    path: '/trainingwheelgame/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherSettingsIndexRoute =
  AuthenticatedTeacherSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherSettingsRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesIndexRoute =
  AuthenticatedTeacherCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedStudentSettingsIndexRoute =
  AuthenticatedStudentSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentSettingsRouteRoute,
  } as any)
const AuthenticatedStudentPaymentMethodsIndexRoute =
  AuthenticatedStudentPaymentMethodsIndexRouteImport.update({
    id: '/payment-methods/',
    path: '/payment-methods/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentInvoicesIndexRoute =
  AuthenticatedStudentInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentCourseTeachersIndexRoute =
  AuthenticatedStudentCourseTeachersIndexRouteImport.update({
    id: '/course-teachers/',
    path: '/course-teachers/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminTrainingwheelgameIndexRoute =
  AuthenticatedAdminTrainingwheelgameIndexRouteImport.update({
    id: '/trainingwheelgame/',
    path: '/trainingwheelgame/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeachersIndexRoute =
  AuthenticatedAdminTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudentsIndexRoute =
  AuthenticatedAdminStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSettingsRouteRoute,
  } as any)
const AuthenticatedStudentCourseTeachersTeacherIDRoute =
  AuthenticatedStudentCourseTeachersTeacherIDRouteImport.update({
    id: '/course-teachers/$teacherID',
    path: '/course-teachers/$teacherID',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminTeachersTeacherIDRoute =
  AuthenticatedAdminTeachersTeacherIDRouteImport.update({
    id: '/teachers/$teacherID',
    path: '/teachers/$teacherID',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIDRoute =
  AuthenticatedAdminCoursesCourseIDRouteImport.update({
    id: '/courses/$courseID',
    path: '/courses/$courseID',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedTeacherTrainingwheelgameCreateIndexRoute =
  AuthenticatedTeacherTrainingwheelgameCreateIndexRouteImport.update({
    id: '/trainingwheelgame/create/',
    path: '/trainingwheelgame/create/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherSettingsProfileIndexRoute =
  AuthenticatedTeacherSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedTeacherSettingsRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesCreate_courseIndexRoute =
  AuthenticatedTeacherCoursesCreate_courseIndexRouteImport.update({
    id: '/courses/create_course/',
    path: '/courses/create_course/',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedStudentSettingsBillingIndexRoute =
  AuthenticatedStudentSettingsBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedStudentSettingsRouteRoute,
  } as any)
const AuthenticatedStudentSubscribedTrainingwheelgameIndexRoute =
  AuthenticatedStudentSubscribedTrainingwheelgameIndexRouteImport.update({
    id: '/trainingwheelgame/',
    path: '/trainingwheelgame/',
    getParentRoute: () => AuthenticatedStudentSubscribedRouteRoute,
  } as any)
const AuthenticatedStudentSubscribedEnrolledcoursesIndexRoute =
  AuthenticatedStudentSubscribedEnrolledcoursesIndexRouteImport.update({
    id: '/enrolledcourses/',
    path: '/enrolledcourses/',
    getParentRoute: () => AuthenticatedStudentSubscribedRouteRoute,
  } as any)
const AuthenticatedAdminTrainingwheelgameCreateIndexRoute =
  AuthenticatedAdminTrainingwheelgameCreateIndexRouteImport.update({
    id: '/trainingwheelgame/create/',
    path: '/trainingwheelgame/create/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsProfileIndexRoute =
  AuthenticatedAdminSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedAdminSettingsRouteRoute,
  } as any)
const AuthenticatedAdminSettingsGameCategoryIndexRoute =
  AuthenticatedAdminSettingsGameCategoryIndexRouteImport.update({
    id: '/game-category/',
    path: '/game-category/',
    getParentRoute: () => AuthenticatedAdminSettingsRouteRoute,
  } as any)
const AuthenticatedAdminSettingsCourseCategoryIndexRoute =
  AuthenticatedAdminSettingsCourseCategoryIndexRouteImport.update({
    id: '/course-category/',
    path: '/course-category/',
    getParentRoute: () => AuthenticatedAdminSettingsRouteRoute,
  } as any)
const AuthenticatedAdminBlogsCreateIndexRoute =
  AuthenticatedAdminBlogsCreateIndexRouteImport.update({
    id: '/blogs/create/',
    path: '/blogs/create/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const StudentSettingInvoicesInvoiceDetailsInvoiceIDRoute =
  StudentSettingInvoicesInvoiceDetailsInvoiceIDRouteImport.update({
    id: '/setting/invoices/invoice-details/$invoiceID',
    path: '/setting/invoices/invoice-details/$invoiceID',
    getParentRoute: () => StudentRouteRoute,
  } as any)
const AuthenticatedTeacherTrainingwheelgameEditGameIDRoute =
  AuthenticatedTeacherTrainingwheelgameEditGameIDRouteImport.update({
    id: '/trainingwheelgame/edit/$gameID',
    path: '/trainingwheelgame/edit/$gameID',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesEdit_courseCourseIdRoute =
  AuthenticatedTeacherCoursesEdit_courseCourseIdRouteImport.update({
    id: '/courses/edit_course/$courseId',
    path: '/courses/edit_course/$courseId',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesCourse_studentsCourseIdRoute =
  AuthenticatedTeacherCoursesCourse_studentsCourseIdRouteImport.update({
    id: '/courses/course_students/$courseId',
    path: '/courses/course_students/$courseId',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesCourse_detailsCourseIDRoute =
  AuthenticatedTeacherCoursesCourse_detailsCourseIDRouteImport.update({
    id: '/courses/course_details/$courseID',
    path: '/courses/course_details/$courseID',
    getParentRoute: () => AuthenticatedTeacherRouteRoute,
  } as any)
const AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRoute =
  AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRouteImport.update({
    id: '/enrolledcourses/$courseId',
    path: '/enrolledcourses/$courseId',
    getParentRoute: () => AuthenticatedStudentSubscribedRouteRoute,
  } as any)
const AuthenticatedAdminTrainingwheelgameEditGameIDRoute =
  AuthenticatedAdminTrainingwheelgameEditGameIDRouteImport.update({
    id: '/trainingwheelgame/edit/$gameID',
    path: '/trainingwheelgame/edit/$gameID',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesErrorsUnauthorizedRoute =
  AuthenticatedAdminSamplePagesErrorsUnauthorizedRouteImport.update({
    id: '/sample-pages/errors/unauthorized',
    path: '/sample-pages/errors/unauthorized',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesErrorsServerErrorRoute =
  AuthenticatedAdminSamplePagesErrorsServerErrorRouteImport.update({
    id: '/sample-pages/errors/server-error',
    path: '/sample-pages/errors/server-error',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesErrorsNotFoundRoute =
  AuthenticatedAdminSamplePagesErrorsNotFoundRouteImport.update({
    id: '/sample-pages/errors/not-found',
    path: '/sample-pages/errors/not-found',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRoute =
  AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRouteImport.update({
    id: '/sample-pages/errors/maintenance-error',
    path: '/sample-pages/errors/maintenance-error',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesErrorsForbiddenRoute =
  AuthenticatedAdminSamplePagesErrorsForbiddenRouteImport.update({
    id: '/sample-pages/errors/forbidden',
    path: '/sample-pages/errors/forbidden',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesAuthSignInRoute =
  AuthenticatedAdminSamplePagesAuthSignInRouteImport.update({
    id: '/sample-pages/auth/sign-in',
    path: '/sample-pages/auth/sign-in',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesAuthOtpRoute =
  AuthenticatedAdminSamplePagesAuthOtpRouteImport.update({
    id: '/sample-pages/auth/otp',
    path: '/sample-pages/auth/otp',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesAuthForgotPasswordRoute =
  AuthenticatedAdminSamplePagesAuthForgotPasswordRouteImport.update({
    id: '/sample-pages/auth/forgot-password',
    path: '/sample-pages/auth/forgot-password',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogsEditBlogIDRoute =
  AuthenticatedAdminBlogsEditBlogIDRouteImport.update({
    id: '/blogs/edit/$blogID',
    path: '/blogs/edit/$blogID',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogsBlogDetailsBlogIDRoute =
  AuthenticatedAdminBlogsBlogDetailsBlogIDRouteImport.update({
    id: '/blogs/blog-details/$blogID',
    path: '/blogs/blog-details/$blogID',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesAuthStudentSignUpRoute =
  AuthenticatedAdminSamplePagesAuthStudentSignUpRouteImport.update({
    id: '/sample-pages/auth/student/sign-up',
    path: '/sample-pages/auth/student/sign-up',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSamplePagesAuthStudentcopySignUpRoute =
  AuthenticatedAdminSamplePagesAuthStudentcopySignUpRouteImport.update({
    id: '/sample-pages/auth/student copy/sign-up',
    path: '/sample-pages/auth/student copy/sign-up',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof AuthenticatedStudentSubscribedRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/student/failed-subscription': typeof StudentFailedSubscriptionRoute
  '/student/forgot-password': typeof StudentForgotPasswordRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/resubscription-plans': typeof StudentResubscriptionPlansRoute
  '/student/subscription-plans': typeof StudentSubscriptionPlansRoute
  '/teacher/forgot-password': typeof TeacherForgotPasswordRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/register': typeof TeacherRegisterRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteRouteWithChildren
  '/student/settings': typeof AuthenticatedStudentSettingsRouteRouteWithChildren
  '/teacher/settings': typeof AuthenticatedTeacherSettingsRouteRouteWithChildren
  '/student/courses/$courseID': typeof StudentCoursesCourseIDRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/quiz': typeof StudentQuizIndexRoute
  '/admin/courses/$courseID': typeof AuthenticatedAdminCoursesCourseIDRoute
  '/admin/teachers/$teacherID': typeof AuthenticatedAdminTeachersTeacherIDRoute
  '/student/course-teachers/$teacherID': typeof AuthenticatedStudentCourseTeachersTeacherIDRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/students': typeof AuthenticatedAdminStudentsIndexRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersIndexRoute
  '/admin/trainingwheelgame': typeof AuthenticatedAdminTrainingwheelgameIndexRoute
  '/student/course-teachers': typeof AuthenticatedStudentCourseTeachersIndexRoute
  '/student/invoices': typeof AuthenticatedStudentInvoicesIndexRoute
  '/student/payment-methods': typeof AuthenticatedStudentPaymentMethodsIndexRoute
  '/student/settings/': typeof AuthenticatedStudentSettingsIndexRoute
  '/teacher/courses': typeof AuthenticatedTeacherCoursesIndexRoute
  '/teacher/settings/': typeof AuthenticatedTeacherSettingsIndexRoute
  '/teacher/trainingwheelgame': typeof AuthenticatedTeacherTrainingwheelgameIndexRoute
  '/student/setting/invoices': typeof StudentSettingInvoicesIndexRoute
  '/admin/blogs': typeof AuthenticatedAdminBlogsIndexLazyRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexLazyRoute
  '/admin/blogs/blog-details/$blogID': typeof AuthenticatedAdminBlogsBlogDetailsBlogIDRoute
  '/admin/blogs/edit/$blogID': typeof AuthenticatedAdminBlogsEditBlogIDRoute
  '/admin/sample-pages/auth/forgot-password': typeof AuthenticatedAdminSamplePagesAuthForgotPasswordRoute
  '/admin/sample-pages/auth/otp': typeof AuthenticatedAdminSamplePagesAuthOtpRoute
  '/admin/sample-pages/auth/sign-in': typeof AuthenticatedAdminSamplePagesAuthSignInRoute
  '/admin/sample-pages/errors/forbidden': typeof AuthenticatedAdminSamplePagesErrorsForbiddenRoute
  '/admin/sample-pages/errors/maintenance-error': typeof AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRoute
  '/admin/sample-pages/errors/not-found': typeof AuthenticatedAdminSamplePagesErrorsNotFoundRoute
  '/admin/sample-pages/errors/server-error': typeof AuthenticatedAdminSamplePagesErrorsServerErrorRoute
  '/admin/sample-pages/errors/unauthorized': typeof AuthenticatedAdminSamplePagesErrorsUnauthorizedRoute
  '/admin/trainingwheelgame/edit/$gameID': typeof AuthenticatedAdminTrainingwheelgameEditGameIDRoute
  '/student/enrolledcourses/$courseId': typeof AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRoute
  '/teacher/courses/course_details/$courseID': typeof AuthenticatedTeacherCoursesCourse_detailsCourseIDRoute
  '/teacher/courses/course_students/$courseId': typeof AuthenticatedTeacherCoursesCourse_studentsCourseIdRoute
  '/teacher/courses/edit_course/$courseId': typeof AuthenticatedTeacherCoursesEdit_courseCourseIdRoute
  '/teacher/trainingwheelgame/edit/$gameID': typeof AuthenticatedTeacherTrainingwheelgameEditGameIDRoute
  '/student/setting/invoices/invoice-details/$invoiceID': typeof StudentSettingInvoicesInvoiceDetailsInvoiceIDRoute
  '/admin/blogs/create': typeof AuthenticatedAdminBlogsCreateIndexRoute
  '/admin/settings/course-category': typeof AuthenticatedAdminSettingsCourseCategoryIndexRoute
  '/admin/settings/game-category': typeof AuthenticatedAdminSettingsGameCategoryIndexRoute
  '/admin/settings/profile': typeof AuthenticatedAdminSettingsProfileIndexRoute
  '/admin/trainingwheelgame/create': typeof AuthenticatedAdminTrainingwheelgameCreateIndexRoute
  '/student/enrolledcourses': typeof AuthenticatedStudentSubscribedEnrolledcoursesIndexRoute
  '/student/trainingwheelgame': typeof AuthenticatedStudentSubscribedTrainingwheelgameIndexRoute
  '/student/settings/billing': typeof AuthenticatedStudentSettingsBillingIndexRoute
  '/teacher/courses/create_course': typeof AuthenticatedTeacherCoursesCreate_courseIndexRoute
  '/teacher/settings/profile': typeof AuthenticatedTeacherSettingsProfileIndexRoute
  '/teacher/trainingwheelgame/create': typeof AuthenticatedTeacherTrainingwheelgameCreateIndexRoute
  '/admin/sample-pages/auth/student copy/sign-up': typeof AuthenticatedAdminSamplePagesAuthStudentcopySignUpRoute
  '/admin/sample-pages/auth/student/sign-up': typeof AuthenticatedAdminSamplePagesAuthStudentSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/student/failed-subscription': typeof StudentFailedSubscriptionRoute
  '/student/forgot-password': typeof StudentForgotPasswordRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/resubscription-plans': typeof StudentResubscriptionPlansRoute
  '/student/subscription-plans': typeof StudentSubscriptionPlansRoute
  '/teacher/forgot-password': typeof TeacherForgotPasswordRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/register': typeof TeacherRegisterRoute
  '/student/courses/$courseID': typeof StudentCoursesCourseIDRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/student/courses': typeof StudentCoursesIndexRoute
  '/student/quiz': typeof StudentQuizIndexRoute
  '/admin/courses/$courseID': typeof AuthenticatedAdminCoursesCourseIDRoute
  '/admin/teachers/$teacherID': typeof AuthenticatedAdminTeachersTeacherIDRoute
  '/student/course-teachers/$teacherID': typeof AuthenticatedStudentCourseTeachersTeacherIDRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/students': typeof AuthenticatedAdminStudentsIndexRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersIndexRoute
  '/admin/trainingwheelgame': typeof AuthenticatedAdminTrainingwheelgameIndexRoute
  '/student/course-teachers': typeof AuthenticatedStudentCourseTeachersIndexRoute
  '/student/invoices': typeof AuthenticatedStudentInvoicesIndexRoute
  '/student/payment-methods': typeof AuthenticatedStudentPaymentMethodsIndexRoute
  '/student/settings': typeof AuthenticatedStudentSettingsIndexRoute
  '/teacher/courses': typeof AuthenticatedTeacherCoursesIndexRoute
  '/teacher/settings': typeof AuthenticatedTeacherSettingsIndexRoute
  '/teacher/trainingwheelgame': typeof AuthenticatedTeacherTrainingwheelgameIndexRoute
  '/student/setting/invoices': typeof StudentSettingInvoicesIndexRoute
  '/admin/blogs': typeof AuthenticatedAdminBlogsIndexLazyRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexLazyRoute
  '/admin/blogs/blog-details/$blogID': typeof AuthenticatedAdminBlogsBlogDetailsBlogIDRoute
  '/admin/blogs/edit/$blogID': typeof AuthenticatedAdminBlogsEditBlogIDRoute
  '/admin/sample-pages/auth/forgot-password': typeof AuthenticatedAdminSamplePagesAuthForgotPasswordRoute
  '/admin/sample-pages/auth/otp': typeof AuthenticatedAdminSamplePagesAuthOtpRoute
  '/admin/sample-pages/auth/sign-in': typeof AuthenticatedAdminSamplePagesAuthSignInRoute
  '/admin/sample-pages/errors/forbidden': typeof AuthenticatedAdminSamplePagesErrorsForbiddenRoute
  '/admin/sample-pages/errors/maintenance-error': typeof AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRoute
  '/admin/sample-pages/errors/not-found': typeof AuthenticatedAdminSamplePagesErrorsNotFoundRoute
  '/admin/sample-pages/errors/server-error': typeof AuthenticatedAdminSamplePagesErrorsServerErrorRoute
  '/admin/sample-pages/errors/unauthorized': typeof AuthenticatedAdminSamplePagesErrorsUnauthorizedRoute
  '/admin/trainingwheelgame/edit/$gameID': typeof AuthenticatedAdminTrainingwheelgameEditGameIDRoute
  '/student/enrolledcourses/$courseId': typeof AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRoute
  '/teacher/courses/course_details/$courseID': typeof AuthenticatedTeacherCoursesCourse_detailsCourseIDRoute
  '/teacher/courses/course_students/$courseId': typeof AuthenticatedTeacherCoursesCourse_studentsCourseIdRoute
  '/teacher/courses/edit_course/$courseId': typeof AuthenticatedTeacherCoursesEdit_courseCourseIdRoute
  '/teacher/trainingwheelgame/edit/$gameID': typeof AuthenticatedTeacherTrainingwheelgameEditGameIDRoute
  '/student/setting/invoices/invoice-details/$invoiceID': typeof StudentSettingInvoicesInvoiceDetailsInvoiceIDRoute
  '/admin/blogs/create': typeof AuthenticatedAdminBlogsCreateIndexRoute
  '/admin/settings/course-category': typeof AuthenticatedAdminSettingsCourseCategoryIndexRoute
  '/admin/settings/game-category': typeof AuthenticatedAdminSettingsGameCategoryIndexRoute
  '/admin/settings/profile': typeof AuthenticatedAdminSettingsProfileIndexRoute
  '/admin/trainingwheelgame/create': typeof AuthenticatedAdminTrainingwheelgameCreateIndexRoute
  '/student/enrolledcourses': typeof AuthenticatedStudentSubscribedEnrolledcoursesIndexRoute
  '/student/trainingwheelgame': typeof AuthenticatedStudentSubscribedTrainingwheelgameIndexRoute
  '/student/settings/billing': typeof AuthenticatedStudentSettingsBillingIndexRoute
  '/teacher/courses/create_course': typeof AuthenticatedTeacherCoursesCreate_courseIndexRoute
  '/teacher/settings/profile': typeof AuthenticatedTeacherSettingsProfileIndexRoute
  '/teacher/trainingwheelgame/create': typeof AuthenticatedTeacherTrainingwheelgameCreateIndexRoute
  '/admin/sample-pages/auth/student copy/sign-up': typeof AuthenticatedAdminSamplePagesAuthStudentcopySignUpRoute
  '/admin/sample-pages/auth/student/sign-up': typeof AuthenticatedAdminSamplePagesAuthStudentSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/student/failed-subscription': typeof StudentFailedSubscriptionRoute
  '/student/forgot-password': typeof StudentForgotPasswordRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/resubscription-plans': typeof StudentResubscriptionPlansRoute
  '/student/subscription-plans': typeof StudentSubscriptionPlansRoute
  '/teacher/forgot-password': typeof TeacherForgotPasswordRoute
  '/teacher/login': typeof TeacherLoginRoute
  '/teacher/register': typeof TeacherRegisterRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteRouteWithChildren
  '/_authenticated/student/_subscribed': typeof AuthenticatedStudentSubscribedRouteRouteWithChildren
  '/_authenticated/student/settings': typeof AuthenticatedStudentSettingsRouteRouteWithChildren
  '/_authenticated/teacher/settings': typeof AuthenticatedTeacherSettingsRouteRouteWithChildren
  '/student/courses/$courseID': typeof StudentCoursesCourseIDRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/student/courses/': typeof StudentCoursesIndexRoute
  '/student/quiz/': typeof StudentQuizIndexRoute
  '/_authenticated/admin/courses/$courseID': typeof AuthenticatedAdminCoursesCourseIDRoute
  '/_authenticated/admin/teachers/$teacherID': typeof AuthenticatedAdminTeachersTeacherIDRoute
  '/_authenticated/student/course-teachers/$teacherID': typeof AuthenticatedStudentCourseTeachersTeacherIDRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/_authenticated/admin/teachers/': typeof AuthenticatedAdminTeachersIndexRoute
  '/_authenticated/admin/trainingwheelgame/': typeof AuthenticatedAdminTrainingwheelgameIndexRoute
  '/_authenticated/student/course-teachers/': typeof AuthenticatedStudentCourseTeachersIndexRoute
  '/_authenticated/student/invoices/': typeof AuthenticatedStudentInvoicesIndexRoute
  '/_authenticated/student/payment-methods/': typeof AuthenticatedStudentPaymentMethodsIndexRoute
  '/_authenticated/student/settings/': typeof AuthenticatedStudentSettingsIndexRoute
  '/_authenticated/teacher/courses/': typeof AuthenticatedTeacherCoursesIndexRoute
  '/_authenticated/teacher/settings/': typeof AuthenticatedTeacherSettingsIndexRoute
  '/_authenticated/teacher/trainingwheelgame/': typeof AuthenticatedTeacherTrainingwheelgameIndexRoute
  '/student/setting/invoices/': typeof StudentSettingInvoicesIndexRoute
  '/_authenticated/admin/blogs/': typeof AuthenticatedAdminBlogsIndexLazyRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexLazyRoute
  '/_authenticated/admin/blogs/blog-details/$blogID': typeof AuthenticatedAdminBlogsBlogDetailsBlogIDRoute
  '/_authenticated/admin/blogs/edit/$blogID': typeof AuthenticatedAdminBlogsEditBlogIDRoute
  '/_authenticated/admin/sample-pages/auth/forgot-password': typeof AuthenticatedAdminSamplePagesAuthForgotPasswordRoute
  '/_authenticated/admin/sample-pages/auth/otp': typeof AuthenticatedAdminSamplePagesAuthOtpRoute
  '/_authenticated/admin/sample-pages/auth/sign-in': typeof AuthenticatedAdminSamplePagesAuthSignInRoute
  '/_authenticated/admin/sample-pages/errors/forbidden': typeof AuthenticatedAdminSamplePagesErrorsForbiddenRoute
  '/_authenticated/admin/sample-pages/errors/maintenance-error': typeof AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRoute
  '/_authenticated/admin/sample-pages/errors/not-found': typeof AuthenticatedAdminSamplePagesErrorsNotFoundRoute
  '/_authenticated/admin/sample-pages/errors/server-error': typeof AuthenticatedAdminSamplePagesErrorsServerErrorRoute
  '/_authenticated/admin/sample-pages/errors/unauthorized': typeof AuthenticatedAdminSamplePagesErrorsUnauthorizedRoute
  '/_authenticated/admin/trainingwheelgame/edit/$gameID': typeof AuthenticatedAdminTrainingwheelgameEditGameIDRoute
  '/_authenticated/student/_subscribed/enrolledcourses/$courseId': typeof AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRoute
  '/_authenticated/teacher/courses/course_details/$courseID': typeof AuthenticatedTeacherCoursesCourse_detailsCourseIDRoute
  '/_authenticated/teacher/courses/course_students/$courseId': typeof AuthenticatedTeacherCoursesCourse_studentsCourseIdRoute
  '/_authenticated/teacher/courses/edit_course/$courseId': typeof AuthenticatedTeacherCoursesEdit_courseCourseIdRoute
  '/_authenticated/teacher/trainingwheelgame/edit/$gameID': typeof AuthenticatedTeacherTrainingwheelgameEditGameIDRoute
  '/student/setting/invoices/invoice-details/$invoiceID': typeof StudentSettingInvoicesInvoiceDetailsInvoiceIDRoute
  '/_authenticated/admin/blogs/create/': typeof AuthenticatedAdminBlogsCreateIndexRoute
  '/_authenticated/admin/settings/course-category/': typeof AuthenticatedAdminSettingsCourseCategoryIndexRoute
  '/_authenticated/admin/settings/game-category/': typeof AuthenticatedAdminSettingsGameCategoryIndexRoute
  '/_authenticated/admin/settings/profile/': typeof AuthenticatedAdminSettingsProfileIndexRoute
  '/_authenticated/admin/trainingwheelgame/create/': typeof AuthenticatedAdminTrainingwheelgameCreateIndexRoute
  '/_authenticated/student/_subscribed/enrolledcourses/': typeof AuthenticatedStudentSubscribedEnrolledcoursesIndexRoute
  '/_authenticated/student/_subscribed/trainingwheelgame/': typeof AuthenticatedStudentSubscribedTrainingwheelgameIndexRoute
  '/_authenticated/student/settings/billing/': typeof AuthenticatedStudentSettingsBillingIndexRoute
  '/_authenticated/teacher/courses/create_course/': typeof AuthenticatedTeacherCoursesCreate_courseIndexRoute
  '/_authenticated/teacher/settings/profile/': typeof AuthenticatedTeacherSettingsProfileIndexRoute
  '/_authenticated/teacher/trainingwheelgame/create/': typeof AuthenticatedTeacherTrainingwheelgameCreateIndexRoute
  '/_authenticated/admin/sample-pages/auth/student copy/sign-up': typeof AuthenticatedAdminSamplePagesAuthStudentcopySignUpRoute
  '/_authenticated/admin/sample-pages/auth/student/sign-up': typeof AuthenticatedAdminSamplePagesAuthStudentSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student'
    | '/admin'
    | '/teacher'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/new'
    | '/student/failed-subscription'
    | '/student/forgot-password'
    | '/student/login'
    | '/student/register'
    | '/student/resubscription-plans'
    | '/student/subscription-plans'
    | '/teacher/forgot-password'
    | '/teacher/login'
    | '/teacher/register'
    | '/admin/settings'
    | '/student/settings'
    | '/teacher/settings'
    | '/student/courses/$courseID'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/courses'
    | '/student/quiz'
    | '/admin/courses/$courseID'
    | '/admin/teachers/$teacherID'
    | '/student/course-teachers/$teacherID'
    | '/admin/settings/'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/trainingwheelgame'
    | '/student/course-teachers'
    | '/student/invoices'
    | '/student/payment-methods'
    | '/student/settings/'
    | '/teacher/courses'
    | '/teacher/settings/'
    | '/teacher/trainingwheelgame'
    | '/student/setting/invoices'
    | '/admin/blogs'
    | '/admin/courses'
    | '/admin/blogs/blog-details/$blogID'
    | '/admin/blogs/edit/$blogID'
    | '/admin/sample-pages/auth/forgot-password'
    | '/admin/sample-pages/auth/otp'
    | '/admin/sample-pages/auth/sign-in'
    | '/admin/sample-pages/errors/forbidden'
    | '/admin/sample-pages/errors/maintenance-error'
    | '/admin/sample-pages/errors/not-found'
    | '/admin/sample-pages/errors/server-error'
    | '/admin/sample-pages/errors/unauthorized'
    | '/admin/trainingwheelgame/edit/$gameID'
    | '/student/enrolledcourses/$courseId'
    | '/teacher/courses/course_details/$courseID'
    | '/teacher/courses/course_students/$courseId'
    | '/teacher/courses/edit_course/$courseId'
    | '/teacher/trainingwheelgame/edit/$gameID'
    | '/student/setting/invoices/invoice-details/$invoiceID'
    | '/admin/blogs/create'
    | '/admin/settings/course-category'
    | '/admin/settings/game-category'
    | '/admin/settings/profile'
    | '/admin/trainingwheelgame/create'
    | '/student/enrolledcourses'
    | '/student/trainingwheelgame'
    | '/student/settings/billing'
    | '/teacher/courses/create_course'
    | '/teacher/settings/profile'
    | '/teacher/trainingwheelgame/create'
    | '/admin/sample-pages/auth/student copy/sign-up'
    | '/admin/sample-pages/auth/student/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/new'
    | '/student/failed-subscription'
    | '/student/forgot-password'
    | '/student/login'
    | '/student/register'
    | '/student/resubscription-plans'
    | '/student/subscription-plans'
    | '/teacher/forgot-password'
    | '/teacher/login'
    | '/teacher/register'
    | '/student/courses/$courseID'
    | '/admin'
    | '/teacher'
    | '/student/courses'
    | '/student/quiz'
    | '/admin/courses/$courseID'
    | '/admin/teachers/$teacherID'
    | '/student/course-teachers/$teacherID'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/trainingwheelgame'
    | '/student/course-teachers'
    | '/student/invoices'
    | '/student/payment-methods'
    | '/student/settings'
    | '/teacher/courses'
    | '/teacher/settings'
    | '/teacher/trainingwheelgame'
    | '/student/setting/invoices'
    | '/admin/blogs'
    | '/admin/courses'
    | '/admin/blogs/blog-details/$blogID'
    | '/admin/blogs/edit/$blogID'
    | '/admin/sample-pages/auth/forgot-password'
    | '/admin/sample-pages/auth/otp'
    | '/admin/sample-pages/auth/sign-in'
    | '/admin/sample-pages/errors/forbidden'
    | '/admin/sample-pages/errors/maintenance-error'
    | '/admin/sample-pages/errors/not-found'
    | '/admin/sample-pages/errors/server-error'
    | '/admin/sample-pages/errors/unauthorized'
    | '/admin/trainingwheelgame/edit/$gameID'
    | '/student/enrolledcourses/$courseId'
    | '/teacher/courses/course_details/$courseID'
    | '/teacher/courses/course_students/$courseId'
    | '/teacher/courses/edit_course/$courseId'
    | '/teacher/trainingwheelgame/edit/$gameID'
    | '/student/setting/invoices/invoice-details/$invoiceID'
    | '/admin/blogs/create'
    | '/admin/settings/course-category'
    | '/admin/settings/game-category'
    | '/admin/settings/profile'
    | '/admin/trainingwheelgame/create'
    | '/student/enrolledcourses'
    | '/student/trainingwheelgame'
    | '/student/settings/billing'
    | '/teacher/courses/create_course'
    | '/teacher/settings/profile'
    | '/teacher/trainingwheelgame/create'
    | '/admin/sample-pages/auth/student copy/sign-up'
    | '/admin/sample-pages/auth/student/sign-up'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/_authenticated/admin'
    | '/_authenticated/student'
    | '/_authenticated/teacher'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/new'
    | '/student/failed-subscription'
    | '/student/forgot-password'
    | '/student/login'
    | '/student/register'
    | '/student/resubscription-plans'
    | '/student/subscription-plans'
    | '/teacher/forgot-password'
    | '/teacher/login'
    | '/teacher/register'
    | '/_authenticated/admin/settings'
    | '/_authenticated/student/_subscribed'
    | '/_authenticated/student/settings'
    | '/_authenticated/teacher/settings'
    | '/student/courses/$courseID'
    | '/_authenticated/admin/'
    | '/_authenticated/student/'
    | '/_authenticated/teacher/'
    | '/student/courses/'
    | '/student/quiz/'
    | '/_authenticated/admin/courses/$courseID'
    | '/_authenticated/admin/teachers/$teacherID'
    | '/_authenticated/student/course-teachers/$teacherID'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/students/'
    | '/_authenticated/admin/teachers/'
    | '/_authenticated/admin/trainingwheelgame/'
    | '/_authenticated/student/course-teachers/'
    | '/_authenticated/student/invoices/'
    | '/_authenticated/student/payment-methods/'
    | '/_authenticated/student/settings/'
    | '/_authenticated/teacher/courses/'
    | '/_authenticated/teacher/settings/'
    | '/_authenticated/teacher/trainingwheelgame/'
    | '/student/setting/invoices/'
    | '/_authenticated/admin/blogs/'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/blogs/blog-details/$blogID'
    | '/_authenticated/admin/blogs/edit/$blogID'
    | '/_authenticated/admin/sample-pages/auth/forgot-password'
    | '/_authenticated/admin/sample-pages/auth/otp'
    | '/_authenticated/admin/sample-pages/auth/sign-in'
    | '/_authenticated/admin/sample-pages/errors/forbidden'
    | '/_authenticated/admin/sample-pages/errors/maintenance-error'
    | '/_authenticated/admin/sample-pages/errors/not-found'
    | '/_authenticated/admin/sample-pages/errors/server-error'
    | '/_authenticated/admin/sample-pages/errors/unauthorized'
    | '/_authenticated/admin/trainingwheelgame/edit/$gameID'
    | '/_authenticated/student/_subscribed/enrolledcourses/$courseId'
    | '/_authenticated/teacher/courses/course_details/$courseID'
    | '/_authenticated/teacher/courses/course_students/$courseId'
    | '/_authenticated/teacher/courses/edit_course/$courseId'
    | '/_authenticated/teacher/trainingwheelgame/edit/$gameID'
    | '/student/setting/invoices/invoice-details/$invoiceID'
    | '/_authenticated/admin/blogs/create/'
    | '/_authenticated/admin/settings/course-category/'
    | '/_authenticated/admin/settings/game-category/'
    | '/_authenticated/admin/settings/profile/'
    | '/_authenticated/admin/trainingwheelgame/create/'
    | '/_authenticated/student/_subscribed/enrolledcourses/'
    | '/_authenticated/student/_subscribed/trainingwheelgame/'
    | '/_authenticated/student/settings/billing/'
    | '/_authenticated/teacher/courses/create_course/'
    | '/_authenticated/teacher/settings/profile/'
    | '/_authenticated/teacher/trainingwheelgame/create/'
    | '/_authenticated/admin/sample-pages/auth/student copy/sign-up'
    | '/_authenticated/admin/sample-pages/auth/student/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
  AuthenticatedTeacherRouteRoute: typeof AuthenticatedTeacherRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  TeacherForgotPasswordRoute: typeof TeacherForgotPasswordRoute
  TeacherLoginRoute: typeof TeacherLoginRoute
  TeacherRegisterRoute: typeof TeacherRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/register': {
      id: '/teacher/register'
      path: '/teacher/register'
      fullPath: '/teacher/register'
      preLoaderRoute: typeof TeacherRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/login': {
      id: '/teacher/login'
      path: '/teacher/login'
      fullPath: '/teacher/login'
      preLoaderRoute: typeof TeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/forgot-password': {
      id: '/teacher/forgot-password'
      path: '/teacher/forgot-password'
      fullPath: '/teacher/forgot-password'
      preLoaderRoute: typeof TeacherForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/subscription-plans': {
      id: '/student/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/student/subscription-plans'
      preLoaderRoute: typeof StudentSubscriptionPlansRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/resubscription-plans': {
      id: '/student/resubscription-plans'
      path: '/resubscription-plans'
      fullPath: '/student/resubscription-plans'
      preLoaderRoute: typeof StudentResubscriptionPlansRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/register': {
      id: '/student/register'
      path: '/register'
      fullPath: '/student/register'
      preLoaderRoute: typeof StudentRegisterRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/login': {
      id: '/student/login'
      path: '/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/forgot-password': {
      id: '/student/forgot-password'
      path: '/forgot-password'
      fullPath: '/student/forgot-password'
      preLoaderRoute: typeof StudentForgotPasswordRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/failed-subscription': {
      id: '/student/failed-subscription'
      path: '/failed-subscription'
      fullPath: '/student/failed-subscription'
      preLoaderRoute: typeof StudentFailedSubscriptionRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/quiz/': {
      id: '/student/quiz/'
      path: '/quiz'
      fullPath: '/student/quiz'
      preLoaderRoute: typeof StudentQuizIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/courses/': {
      id: '/student/courses/'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/student/courses/$courseID': {
      id: '/student/courses/$courseID'
      path: '/courses/$courseID'
      fullPath: '/student/courses/$courseID'
      preLoaderRoute: typeof StudentCoursesCourseIDRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_authenticated/teacher/settings': {
      id: '/_authenticated/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof AuthenticatedTeacherSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/student/settings': {
      id: '/_authenticated/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof AuthenticatedStudentSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/_subscribed': {
      id: '/_authenticated/student/_subscribed'
      path: ''
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentSubscribedRouteRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexLazyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blogs/': {
      id: '/_authenticated/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AuthenticatedAdminBlogsIndexLazyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/student/setting/invoices/': {
      id: '/student/setting/invoices/'
      path: '/setting/invoices'
      fullPath: '/student/setting/invoices'
      preLoaderRoute: typeof StudentSettingInvoicesIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_authenticated/teacher/trainingwheelgame/': {
      id: '/_authenticated/teacher/trainingwheelgame/'
      path: '/trainingwheelgame'
      fullPath: '/teacher/trainingwheelgame'
      preLoaderRoute: typeof AuthenticatedTeacherTrainingwheelgameIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/settings/': {
      id: '/_authenticated/teacher/settings/'
      path: '/'
      fullPath: '/teacher/settings/'
      preLoaderRoute: typeof AuthenticatedTeacherSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherSettingsRouteRoute
    }
    '/_authenticated/teacher/courses/': {
      id: '/_authenticated/teacher/courses/'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/student/settings/': {
      id: '/_authenticated/student/settings/'
      path: '/'
      fullPath: '/student/settings/'
      preLoaderRoute: typeof AuthenticatedStudentSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentSettingsRouteRoute
    }
    '/_authenticated/student/payment-methods/': {
      id: '/_authenticated/student/payment-methods/'
      path: '/payment-methods'
      fullPath: '/student/payment-methods'
      preLoaderRoute: typeof AuthenticatedStudentPaymentMethodsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/invoices/': {
      id: '/_authenticated/student/invoices/'
      path: '/invoices'
      fullPath: '/student/invoices'
      preLoaderRoute: typeof AuthenticatedStudentInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/course-teachers/': {
      id: '/_authenticated/student/course-teachers/'
      path: '/course-teachers'
      fullPath: '/student/course-teachers'
      preLoaderRoute: typeof AuthenticatedStudentCourseTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/admin/trainingwheelgame/': {
      id: '/_authenticated/admin/trainingwheelgame/'
      path: '/trainingwheelgame'
      fullPath: '/admin/trainingwheelgame'
      preLoaderRoute: typeof AuthenticatedAdminTrainingwheelgameIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/teachers/': {
      id: '/_authenticated/admin/teachers/'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/students/': {
      id: '/_authenticated/admin/students/'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRouteRoute
    }
    '/_authenticated/student/course-teachers/$teacherID': {
      id: '/_authenticated/student/course-teachers/$teacherID'
      path: '/course-teachers/$teacherID'
      fullPath: '/student/course-teachers/$teacherID'
      preLoaderRoute: typeof AuthenticatedStudentCourseTeachersTeacherIDRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/admin/teachers/$teacherID': {
      id: '/_authenticated/admin/teachers/$teacherID'
      path: '/teachers/$teacherID'
      fullPath: '/admin/teachers/$teacherID'
      preLoaderRoute: typeof AuthenticatedAdminTeachersTeacherIDRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses/$courseID': {
      id: '/_authenticated/admin/courses/$courseID'
      path: '/courses/$courseID'
      fullPath: '/admin/courses/$courseID'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIDRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/teacher/trainingwheelgame/create/': {
      id: '/_authenticated/teacher/trainingwheelgame/create/'
      path: '/trainingwheelgame/create'
      fullPath: '/teacher/trainingwheelgame/create'
      preLoaderRoute: typeof AuthenticatedTeacherTrainingwheelgameCreateIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/settings/profile/': {
      id: '/_authenticated/teacher/settings/profile/'
      path: '/profile'
      fullPath: '/teacher/settings/profile'
      preLoaderRoute: typeof AuthenticatedTeacherSettingsProfileIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherSettingsRouteRoute
    }
    '/_authenticated/teacher/courses/create_course/': {
      id: '/_authenticated/teacher/courses/create_course/'
      path: '/courses/create_course'
      fullPath: '/teacher/courses/create_course'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCreate_courseIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/student/settings/billing/': {
      id: '/_authenticated/student/settings/billing/'
      path: '/billing'
      fullPath: '/student/settings/billing'
      preLoaderRoute: typeof AuthenticatedStudentSettingsBillingIndexRouteImport
      parentRoute: typeof AuthenticatedStudentSettingsRouteRoute
    }
    '/_authenticated/student/_subscribed/trainingwheelgame/': {
      id: '/_authenticated/student/_subscribed/trainingwheelgame/'
      path: '/trainingwheelgame'
      fullPath: '/student/trainingwheelgame'
      preLoaderRoute: typeof AuthenticatedStudentSubscribedTrainingwheelgameIndexRouteImport
      parentRoute: typeof AuthenticatedStudentSubscribedRouteRoute
    }
    '/_authenticated/student/_subscribed/enrolledcourses/': {
      id: '/_authenticated/student/_subscribed/enrolledcourses/'
      path: '/enrolledcourses'
      fullPath: '/student/enrolledcourses'
      preLoaderRoute: typeof AuthenticatedStudentSubscribedEnrolledcoursesIndexRouteImport
      parentRoute: typeof AuthenticatedStudentSubscribedRouteRoute
    }
    '/_authenticated/admin/trainingwheelgame/create/': {
      id: '/_authenticated/admin/trainingwheelgame/create/'
      path: '/trainingwheelgame/create'
      fullPath: '/admin/trainingwheelgame/create'
      preLoaderRoute: typeof AuthenticatedAdminTrainingwheelgameCreateIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/profile/': {
      id: '/_authenticated/admin/settings/profile/'
      path: '/profile'
      fullPath: '/admin/settings/profile'
      preLoaderRoute: typeof AuthenticatedAdminSettingsProfileIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRouteRoute
    }
    '/_authenticated/admin/settings/game-category/': {
      id: '/_authenticated/admin/settings/game-category/'
      path: '/game-category'
      fullPath: '/admin/settings/game-category'
      preLoaderRoute: typeof AuthenticatedAdminSettingsGameCategoryIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRouteRoute
    }
    '/_authenticated/admin/settings/course-category/': {
      id: '/_authenticated/admin/settings/course-category/'
      path: '/course-category'
      fullPath: '/admin/settings/course-category'
      preLoaderRoute: typeof AuthenticatedAdminSettingsCourseCategoryIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRouteRoute
    }
    '/_authenticated/admin/blogs/create/': {
      id: '/_authenticated/admin/blogs/create/'
      path: '/blogs/create'
      fullPath: '/admin/blogs/create'
      preLoaderRoute: typeof AuthenticatedAdminBlogsCreateIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/student/setting/invoices/invoice-details/$invoiceID': {
      id: '/student/setting/invoices/invoice-details/$invoiceID'
      path: '/setting/invoices/invoice-details/$invoiceID'
      fullPath: '/student/setting/invoices/invoice-details/$invoiceID'
      preLoaderRoute: typeof StudentSettingInvoicesInvoiceDetailsInvoiceIDRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/_authenticated/teacher/trainingwheelgame/edit/$gameID': {
      id: '/_authenticated/teacher/trainingwheelgame/edit/$gameID'
      path: '/trainingwheelgame/edit/$gameID'
      fullPath: '/teacher/trainingwheelgame/edit/$gameID'
      preLoaderRoute: typeof AuthenticatedTeacherTrainingwheelgameEditGameIDRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/courses/edit_course/$courseId': {
      id: '/_authenticated/teacher/courses/edit_course/$courseId'
      path: '/courses/edit_course/$courseId'
      fullPath: '/teacher/courses/edit_course/$courseId'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesEdit_courseCourseIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/courses/course_students/$courseId': {
      id: '/_authenticated/teacher/courses/course_students/$courseId'
      path: '/courses/course_students/$courseId'
      fullPath: '/teacher/courses/course_students/$courseId'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCourse_studentsCourseIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/teacher/courses/course_details/$courseID': {
      id: '/_authenticated/teacher/courses/course_details/$courseID'
      path: '/courses/course_details/$courseID'
      fullPath: '/teacher/courses/course_details/$courseID'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCourse_detailsCourseIDRouteImport
      parentRoute: typeof AuthenticatedTeacherRouteRoute
    }
    '/_authenticated/student/_subscribed/enrolledcourses/$courseId': {
      id: '/_authenticated/student/_subscribed/enrolledcourses/$courseId'
      path: '/enrolledcourses/$courseId'
      fullPath: '/student/enrolledcourses/$courseId'
      preLoaderRoute: typeof AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedStudentSubscribedRouteRoute
    }
    '/_authenticated/admin/trainingwheelgame/edit/$gameID': {
      id: '/_authenticated/admin/trainingwheelgame/edit/$gameID'
      path: '/trainingwheelgame/edit/$gameID'
      fullPath: '/admin/trainingwheelgame/edit/$gameID'
      preLoaderRoute: typeof AuthenticatedAdminTrainingwheelgameEditGameIDRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/errors/unauthorized': {
      id: '/_authenticated/admin/sample-pages/errors/unauthorized'
      path: '/sample-pages/errors/unauthorized'
      fullPath: '/admin/sample-pages/errors/unauthorized'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesErrorsUnauthorizedRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/errors/server-error': {
      id: '/_authenticated/admin/sample-pages/errors/server-error'
      path: '/sample-pages/errors/server-error'
      fullPath: '/admin/sample-pages/errors/server-error'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesErrorsServerErrorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/errors/not-found': {
      id: '/_authenticated/admin/sample-pages/errors/not-found'
      path: '/sample-pages/errors/not-found'
      fullPath: '/admin/sample-pages/errors/not-found'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesErrorsNotFoundRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/errors/maintenance-error': {
      id: '/_authenticated/admin/sample-pages/errors/maintenance-error'
      path: '/sample-pages/errors/maintenance-error'
      fullPath: '/admin/sample-pages/errors/maintenance-error'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/errors/forbidden': {
      id: '/_authenticated/admin/sample-pages/errors/forbidden'
      path: '/sample-pages/errors/forbidden'
      fullPath: '/admin/sample-pages/errors/forbidden'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesErrorsForbiddenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/auth/sign-in': {
      id: '/_authenticated/admin/sample-pages/auth/sign-in'
      path: '/sample-pages/auth/sign-in'
      fullPath: '/admin/sample-pages/auth/sign-in'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesAuthSignInRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/auth/otp': {
      id: '/_authenticated/admin/sample-pages/auth/otp'
      path: '/sample-pages/auth/otp'
      fullPath: '/admin/sample-pages/auth/otp'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesAuthOtpRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/auth/forgot-password': {
      id: '/_authenticated/admin/sample-pages/auth/forgot-password'
      path: '/sample-pages/auth/forgot-password'
      fullPath: '/admin/sample-pages/auth/forgot-password'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesAuthForgotPasswordRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blogs/edit/$blogID': {
      id: '/_authenticated/admin/blogs/edit/$blogID'
      path: '/blogs/edit/$blogID'
      fullPath: '/admin/blogs/edit/$blogID'
      preLoaderRoute: typeof AuthenticatedAdminBlogsEditBlogIDRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blogs/blog-details/$blogID': {
      id: '/_authenticated/admin/blogs/blog-details/$blogID'
      path: '/blogs/blog-details/$blogID'
      fullPath: '/admin/blogs/blog-details/$blogID'
      preLoaderRoute: typeof AuthenticatedAdminBlogsBlogDetailsBlogIDRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/auth/student/sign-up': {
      id: '/_authenticated/admin/sample-pages/auth/student/sign-up'
      path: '/sample-pages/auth/student/sign-up'
      fullPath: '/admin/sample-pages/auth/student/sign-up'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesAuthStudentSignUpRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sample-pages/auth/student copy/sign-up': {
      id: '/_authenticated/admin/sample-pages/auth/student copy/sign-up'
      path: '/sample-pages/auth/student copy/sign-up'
      fullPath: '/admin/sample-pages/auth/student copy/sign-up'
      preLoaderRoute: typeof AuthenticatedAdminSamplePagesAuthStudentcopySignUpRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface StudentRouteRouteChildren {
  StudentFailedSubscriptionRoute: typeof StudentFailedSubscriptionRoute
  StudentForgotPasswordRoute: typeof StudentForgotPasswordRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentRegisterRoute: typeof StudentRegisterRoute
  StudentResubscriptionPlansRoute: typeof StudentResubscriptionPlansRoute
  StudentSubscriptionPlansRoute: typeof StudentSubscriptionPlansRoute
  StudentCoursesCourseIDRoute: typeof StudentCoursesCourseIDRoute
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
  StudentQuizIndexRoute: typeof StudentQuizIndexRoute
  StudentSettingInvoicesIndexRoute: typeof StudentSettingInvoicesIndexRoute
  StudentSettingInvoicesInvoiceDetailsInvoiceIDRoute: typeof StudentSettingInvoicesInvoiceDetailsInvoiceIDRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentFailedSubscriptionRoute: StudentFailedSubscriptionRoute,
  StudentForgotPasswordRoute: StudentForgotPasswordRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentRegisterRoute: StudentRegisterRoute,
  StudentResubscriptionPlansRoute: StudentResubscriptionPlansRoute,
  StudentSubscriptionPlansRoute: StudentSubscriptionPlansRoute,
  StudentCoursesCourseIDRoute: StudentCoursesCourseIDRoute,
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
  StudentQuizIndexRoute: StudentQuizIndexRoute,
  StudentSettingInvoicesIndexRoute: StudentSettingInvoicesIndexRoute,
  StudentSettingInvoicesInvoiceDetailsInvoiceIDRoute:
    StudentSettingInvoicesInvoiceDetailsInvoiceIDRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface AuthenticatedAdminSettingsRouteRouteChildren {
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminSettingsCourseCategoryIndexRoute: typeof AuthenticatedAdminSettingsCourseCategoryIndexRoute
  AuthenticatedAdminSettingsGameCategoryIndexRoute: typeof AuthenticatedAdminSettingsGameCategoryIndexRoute
  AuthenticatedAdminSettingsProfileIndexRoute: typeof AuthenticatedAdminSettingsProfileIndexRoute
}

const AuthenticatedAdminSettingsRouteRouteChildren: AuthenticatedAdminSettingsRouteRouteChildren =
  {
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
    AuthenticatedAdminSettingsCourseCategoryIndexRoute:
      AuthenticatedAdminSettingsCourseCategoryIndexRoute,
    AuthenticatedAdminSettingsGameCategoryIndexRoute:
      AuthenticatedAdminSettingsGameCategoryIndexRoute,
    AuthenticatedAdminSettingsProfileIndexRoute:
      AuthenticatedAdminSettingsProfileIndexRoute,
  }

const AuthenticatedAdminSettingsRouteRouteWithChildren =
  AuthenticatedAdminSettingsRouteRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSettingsRouteRoute: typeof AuthenticatedAdminSettingsRouteRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCoursesCourseIDRoute: typeof AuthenticatedAdminCoursesCourseIDRoute
  AuthenticatedAdminTeachersTeacherIDRoute: typeof AuthenticatedAdminTeachersTeacherIDRoute
  AuthenticatedAdminStudentsIndexRoute: typeof AuthenticatedAdminStudentsIndexRoute
  AuthenticatedAdminTeachersIndexRoute: typeof AuthenticatedAdminTeachersIndexRoute
  AuthenticatedAdminTrainingwheelgameIndexRoute: typeof AuthenticatedAdminTrainingwheelgameIndexRoute
  AuthenticatedAdminBlogsIndexLazyRoute: typeof AuthenticatedAdminBlogsIndexLazyRoute
  AuthenticatedAdminCoursesIndexLazyRoute: typeof AuthenticatedAdminCoursesIndexLazyRoute
  AuthenticatedAdminBlogsBlogDetailsBlogIDRoute: typeof AuthenticatedAdminBlogsBlogDetailsBlogIDRoute
  AuthenticatedAdminBlogsEditBlogIDRoute: typeof AuthenticatedAdminBlogsEditBlogIDRoute
  AuthenticatedAdminSamplePagesAuthForgotPasswordRoute: typeof AuthenticatedAdminSamplePagesAuthForgotPasswordRoute
  AuthenticatedAdminSamplePagesAuthOtpRoute: typeof AuthenticatedAdminSamplePagesAuthOtpRoute
  AuthenticatedAdminSamplePagesAuthSignInRoute: typeof AuthenticatedAdminSamplePagesAuthSignInRoute
  AuthenticatedAdminSamplePagesErrorsForbiddenRoute: typeof AuthenticatedAdminSamplePagesErrorsForbiddenRoute
  AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRoute: typeof AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRoute
  AuthenticatedAdminSamplePagesErrorsNotFoundRoute: typeof AuthenticatedAdminSamplePagesErrorsNotFoundRoute
  AuthenticatedAdminSamplePagesErrorsServerErrorRoute: typeof AuthenticatedAdminSamplePagesErrorsServerErrorRoute
  AuthenticatedAdminSamplePagesErrorsUnauthorizedRoute: typeof AuthenticatedAdminSamplePagesErrorsUnauthorizedRoute
  AuthenticatedAdminTrainingwheelgameEditGameIDRoute: typeof AuthenticatedAdminTrainingwheelgameEditGameIDRoute
  AuthenticatedAdminBlogsCreateIndexRoute: typeof AuthenticatedAdminBlogsCreateIndexRoute
  AuthenticatedAdminTrainingwheelgameCreateIndexRoute: typeof AuthenticatedAdminTrainingwheelgameCreateIndexRoute
  AuthenticatedAdminSamplePagesAuthStudentcopySignUpRoute: typeof AuthenticatedAdminSamplePagesAuthStudentcopySignUpRoute
  AuthenticatedAdminSamplePagesAuthStudentSignUpRoute: typeof AuthenticatedAdminSamplePagesAuthStudentSignUpRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSettingsRouteRoute:
      AuthenticatedAdminSettingsRouteRouteWithChildren,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCoursesCourseIDRoute:
      AuthenticatedAdminCoursesCourseIDRoute,
    AuthenticatedAdminTeachersTeacherIDRoute:
      AuthenticatedAdminTeachersTeacherIDRoute,
    AuthenticatedAdminStudentsIndexRoute: AuthenticatedAdminStudentsIndexRoute,
    AuthenticatedAdminTeachersIndexRoute: AuthenticatedAdminTeachersIndexRoute,
    AuthenticatedAdminTrainingwheelgameIndexRoute:
      AuthenticatedAdminTrainingwheelgameIndexRoute,
    AuthenticatedAdminBlogsIndexLazyRoute:
      AuthenticatedAdminBlogsIndexLazyRoute,
    AuthenticatedAdminCoursesIndexLazyRoute:
      AuthenticatedAdminCoursesIndexLazyRoute,
    AuthenticatedAdminBlogsBlogDetailsBlogIDRoute:
      AuthenticatedAdminBlogsBlogDetailsBlogIDRoute,
    AuthenticatedAdminBlogsEditBlogIDRoute:
      AuthenticatedAdminBlogsEditBlogIDRoute,
    AuthenticatedAdminSamplePagesAuthForgotPasswordRoute:
      AuthenticatedAdminSamplePagesAuthForgotPasswordRoute,
    AuthenticatedAdminSamplePagesAuthOtpRoute:
      AuthenticatedAdminSamplePagesAuthOtpRoute,
    AuthenticatedAdminSamplePagesAuthSignInRoute:
      AuthenticatedAdminSamplePagesAuthSignInRoute,
    AuthenticatedAdminSamplePagesErrorsForbiddenRoute:
      AuthenticatedAdminSamplePagesErrorsForbiddenRoute,
    AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRoute:
      AuthenticatedAdminSamplePagesErrorsMaintenanceErrorRoute,
    AuthenticatedAdminSamplePagesErrorsNotFoundRoute:
      AuthenticatedAdminSamplePagesErrorsNotFoundRoute,
    AuthenticatedAdminSamplePagesErrorsServerErrorRoute:
      AuthenticatedAdminSamplePagesErrorsServerErrorRoute,
    AuthenticatedAdminSamplePagesErrorsUnauthorizedRoute:
      AuthenticatedAdminSamplePagesErrorsUnauthorizedRoute,
    AuthenticatedAdminTrainingwheelgameEditGameIDRoute:
      AuthenticatedAdminTrainingwheelgameEditGameIDRoute,
    AuthenticatedAdminBlogsCreateIndexRoute:
      AuthenticatedAdminBlogsCreateIndexRoute,
    AuthenticatedAdminTrainingwheelgameCreateIndexRoute:
      AuthenticatedAdminTrainingwheelgameCreateIndexRoute,
    AuthenticatedAdminSamplePagesAuthStudentcopySignUpRoute:
      AuthenticatedAdminSamplePagesAuthStudentcopySignUpRoute,
    AuthenticatedAdminSamplePagesAuthStudentSignUpRoute:
      AuthenticatedAdminSamplePagesAuthStudentSignUpRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedStudentSubscribedRouteRouteChildren {
  AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRoute: typeof AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRoute
  AuthenticatedStudentSubscribedEnrolledcoursesIndexRoute: typeof AuthenticatedStudentSubscribedEnrolledcoursesIndexRoute
  AuthenticatedStudentSubscribedTrainingwheelgameIndexRoute: typeof AuthenticatedStudentSubscribedTrainingwheelgameIndexRoute
}

const AuthenticatedStudentSubscribedRouteRouteChildren: AuthenticatedStudentSubscribedRouteRouteChildren =
  {
    AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRoute:
      AuthenticatedStudentSubscribedEnrolledcoursesCourseIdRoute,
    AuthenticatedStudentSubscribedEnrolledcoursesIndexRoute:
      AuthenticatedStudentSubscribedEnrolledcoursesIndexRoute,
    AuthenticatedStudentSubscribedTrainingwheelgameIndexRoute:
      AuthenticatedStudentSubscribedTrainingwheelgameIndexRoute,
  }

const AuthenticatedStudentSubscribedRouteRouteWithChildren =
  AuthenticatedStudentSubscribedRouteRoute._addFileChildren(
    AuthenticatedStudentSubscribedRouteRouteChildren,
  )

interface AuthenticatedStudentSettingsRouteRouteChildren {
  AuthenticatedStudentSettingsIndexRoute: typeof AuthenticatedStudentSettingsIndexRoute
  AuthenticatedStudentSettingsBillingIndexRoute: typeof AuthenticatedStudentSettingsBillingIndexRoute
}

const AuthenticatedStudentSettingsRouteRouteChildren: AuthenticatedStudentSettingsRouteRouteChildren =
  {
    AuthenticatedStudentSettingsIndexRoute:
      AuthenticatedStudentSettingsIndexRoute,
    AuthenticatedStudentSettingsBillingIndexRoute:
      AuthenticatedStudentSettingsBillingIndexRoute,
  }

const AuthenticatedStudentSettingsRouteRouteWithChildren =
  AuthenticatedStudentSettingsRouteRoute._addFileChildren(
    AuthenticatedStudentSettingsRouteRouteChildren,
  )

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentSubscribedRouteRoute: typeof AuthenticatedStudentSubscribedRouteRouteWithChildren
  AuthenticatedStudentSettingsRouteRoute: typeof AuthenticatedStudentSettingsRouteRouteWithChildren
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedStudentCourseTeachersTeacherIDRoute: typeof AuthenticatedStudentCourseTeachersTeacherIDRoute
  AuthenticatedStudentCourseTeachersIndexRoute: typeof AuthenticatedStudentCourseTeachersIndexRoute
  AuthenticatedStudentInvoicesIndexRoute: typeof AuthenticatedStudentInvoicesIndexRoute
  AuthenticatedStudentPaymentMethodsIndexRoute: typeof AuthenticatedStudentPaymentMethodsIndexRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentSubscribedRouteRoute:
      AuthenticatedStudentSubscribedRouteRouteWithChildren,
    AuthenticatedStudentSettingsRouteRoute:
      AuthenticatedStudentSettingsRouteRouteWithChildren,
    AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
    AuthenticatedStudentCourseTeachersTeacherIDRoute:
      AuthenticatedStudentCourseTeachersTeacherIDRoute,
    AuthenticatedStudentCourseTeachersIndexRoute:
      AuthenticatedStudentCourseTeachersIndexRoute,
    AuthenticatedStudentInvoicesIndexRoute:
      AuthenticatedStudentInvoicesIndexRoute,
    AuthenticatedStudentPaymentMethodsIndexRoute:
      AuthenticatedStudentPaymentMethodsIndexRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedTeacherSettingsRouteRouteChildren {
  AuthenticatedTeacherSettingsIndexRoute: typeof AuthenticatedTeacherSettingsIndexRoute
  AuthenticatedTeacherSettingsProfileIndexRoute: typeof AuthenticatedTeacherSettingsProfileIndexRoute
}

const AuthenticatedTeacherSettingsRouteRouteChildren: AuthenticatedTeacherSettingsRouteRouteChildren =
  {
    AuthenticatedTeacherSettingsIndexRoute:
      AuthenticatedTeacherSettingsIndexRoute,
    AuthenticatedTeacherSettingsProfileIndexRoute:
      AuthenticatedTeacherSettingsProfileIndexRoute,
  }

const AuthenticatedTeacherSettingsRouteRouteWithChildren =
  AuthenticatedTeacherSettingsRouteRoute._addFileChildren(
    AuthenticatedTeacherSettingsRouteRouteChildren,
  )

interface AuthenticatedTeacherRouteRouteChildren {
  AuthenticatedTeacherSettingsRouteRoute: typeof AuthenticatedTeacherSettingsRouteRouteWithChildren
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedTeacherCoursesIndexRoute: typeof AuthenticatedTeacherCoursesIndexRoute
  AuthenticatedTeacherTrainingwheelgameIndexRoute: typeof AuthenticatedTeacherTrainingwheelgameIndexRoute
  AuthenticatedTeacherCoursesCourse_detailsCourseIDRoute: typeof AuthenticatedTeacherCoursesCourse_detailsCourseIDRoute
  AuthenticatedTeacherCoursesCourse_studentsCourseIdRoute: typeof AuthenticatedTeacherCoursesCourse_studentsCourseIdRoute
  AuthenticatedTeacherCoursesEdit_courseCourseIdRoute: typeof AuthenticatedTeacherCoursesEdit_courseCourseIdRoute
  AuthenticatedTeacherTrainingwheelgameEditGameIDRoute: typeof AuthenticatedTeacherTrainingwheelgameEditGameIDRoute
  AuthenticatedTeacherCoursesCreate_courseIndexRoute: typeof AuthenticatedTeacherCoursesCreate_courseIndexRoute
  AuthenticatedTeacherTrainingwheelgameCreateIndexRoute: typeof AuthenticatedTeacherTrainingwheelgameCreateIndexRoute
}

const AuthenticatedTeacherRouteRouteChildren: AuthenticatedTeacherRouteRouteChildren =
  {
    AuthenticatedTeacherSettingsRouteRoute:
      AuthenticatedTeacherSettingsRouteRouteWithChildren,
    AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
    AuthenticatedTeacherCoursesIndexRoute:
      AuthenticatedTeacherCoursesIndexRoute,
    AuthenticatedTeacherTrainingwheelgameIndexRoute:
      AuthenticatedTeacherTrainingwheelgameIndexRoute,
    AuthenticatedTeacherCoursesCourse_detailsCourseIDRoute:
      AuthenticatedTeacherCoursesCourse_detailsCourseIDRoute,
    AuthenticatedTeacherCoursesCourse_studentsCourseIdRoute:
      AuthenticatedTeacherCoursesCourse_studentsCourseIdRoute,
    AuthenticatedTeacherCoursesEdit_courseCourseIdRoute:
      AuthenticatedTeacherCoursesEdit_courseCourseIdRoute,
    AuthenticatedTeacherTrainingwheelgameEditGameIDRoute:
      AuthenticatedTeacherTrainingwheelgameEditGameIDRoute,
    AuthenticatedTeacherCoursesCreate_courseIndexRoute:
      AuthenticatedTeacherCoursesCreate_courseIndexRoute,
    AuthenticatedTeacherTrainingwheelgameCreateIndexRoute:
      AuthenticatedTeacherTrainingwheelgameCreateIndexRoute,
  }

const AuthenticatedTeacherRouteRouteWithChildren =
  AuthenticatedTeacherRouteRoute._addFileChildren(
    AuthenticatedTeacherRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedTeacherRouteRoute: AuthenticatedTeacherRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  TeacherForgotPasswordRoute: TeacherForgotPasswordRoute,
  TeacherLoginRoute: TeacherLoginRoute,
  TeacherRegisterRoute: TeacherRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
